name: frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Icons & UI Enhancements
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package to enforce best practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment below if you have assets like images or JSON files
  # assets:
  #   - assets/images/
  #   - assets/data/

  # Uncomment below if you use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700